---
# tasks file for create_file_sd

- name: Generate the file_sd_configs for prometheus
  template:
    src: sd_file_configs.yml.j2
    dest: /etc/prometheus/custom_sd/file_sd_configs.yml
    owner: prometheus
    group: prometheus
    mode: u=rw,g=r,o=r
