---
# tasks file for create_file_sd

- name: Generate the file_sd_configs for prometheus
  template:
    src: sd_file_configs.yml.j2
    dest: /etc/prometheus/node_exporter.yml
    mode: u=rw,g=r,o=r
